#! /bin/sh
### BEGIN INIT INFO
# Provides:          Ampsoft
# Required-Start: 
# Required-Stop: 
# Should-Start:	     
# Should_Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6	     
# Short-Description: Starting/stoping script for Rygel
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/local/bin:/usr/bin:

PYTHONPID=`pidof -s python` 

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
	echo "Starting amplifier..."
	python /root/ampsoft/main.py &
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;

   stop)
	echo "Stopping amplifier..."
	i2cset -y 0 0x39 0x01 0x00
	kill $PYTHONPID
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
