#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>System Info for $(hostname -s)</title>"
echo "<link rel="stylesheet" type="text/css" href="../style/style.css" />"
echo "</head>"
echo "<h1General system informations for host $(hostname -s)</h1>"
echo "<pre>OS $(uname -srm)</pre>"
echo "<h2>Audio hardware parameters</h2>"
echo "<pre>$(cat /proc/asound/card0/pcm0p/info | grep id)</pre>"
echo "<pre>$(cat /proc/asound/card0/pcm0p/sub0/hw_params)</pre>"
echo "<h2>Uptime</h2>"
echo "<pre>$(uptime)</pre>"
echo "<h2>USB Devices</h2>"
echo "<pre>$(lsusb)</pre>"
echo "<h2>Disk Info</h2>"
echo "<pre>$(df -h)</pre>"
echo "<h2>Memory Info</h2>"
echo "<pre>$(free -m)</pre>"
echo "<h2>Network Info</h2>"
echo "Interfaces"
echo "<pre>$(ifconfig)</pre>"
echo "Wireless"
echo "<pre>$(iwconfig)</pre>"
echo "<h2>Logged in user</h2>"
echo "<pre>$(w)</pre>"
echo "<center>Informations generated on $(date)</center>"
echo "</body></html>"